from petri_nets.PetriNet import PetriNet

body_main_petri_net = PetriNet()



body_main_petri_net.add_place("P1", "Zlecenie panelu", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P2", "Zlecenie panelu\ngórnego", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P3", "Zlecenie sterowania\nklimatyzacją", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P4", "Tworzenie i instalacja\nsterowania klimatyzacją\n4-warstwową", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P5", "Gotowy panel\ngórny", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P6", "Gotowy panel", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P7", "Gotowy korpus", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P8", "Tworzenie i instalacja\nsterowania klimatyzacją\n2-warstwową", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P9", "Tworzenie i instalacja\npanelu górnego bez\nsterowania klimatyzacją", tokens=0, max_tokens=5)

body_main_petri_net.add_place("P10", "Zlecenie panelu\nśrodkowego", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P11", "Tworzenie i instalacja\ninterfejsu\nmultimedialnego", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P12", "Gotowy panel\nśrodkowy", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P13", "Tworzenie i instalacja\nschowka", tokens=0, max_tokens=5)

body_main_petri_net.add_place("P14", "Zlecenie panelu\ndolnego", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P15", "Tworzenie i instalacja\nładowarki\nbezprzewodowej", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P16", "Zlecenie miejsca\nna kubki", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P17", "Tworzenie i instalacja\nmiejsca na\nkubki", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P18", "Zlecenie kolorowania", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P19", "Malowanie na kolor\nczerwony", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P20", "Gotowy panel\ndolny", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P21", "Tworzenie i instalacja\nładowarki\npółki", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P22", "Tworzenie i instalacja\nbraku miejsca na\nkubki", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P23", "Malowanie na kolor\nzielony", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P24", "Malowanie na kolor\nniebieski", tokens=0, max_tokens=5)

body_main_petri_net.add_place("P25", "Zlecenie podłokietnika\n", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P26", "Wycinanie ze skóry", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P27", "Zlecenie kolorowania", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P28", "Tworzenie i instalacja\npodgrzewania podłokietnika", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P29", "Zlecenie kolorowania", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P30", "Malowanie na kolor\nczerwony", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P31", "Gotowy podłokietnik", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P32", "Wycinanie z eko-skóry", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P33", "Tworzenie i instalacja\npodłokietnika bez\nogrzewania", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P34", "Malowanie na kolor\nzielony", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P35", "Wycinanie ze sztucznej\nskóry", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P36", "Malowanie na kolor\nniebieski", tokens=0, max_tokens=5)

body_main_petri_net.add_place("P37", "Zlecenie uchwytu", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P38", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P39", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P40", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P41", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P42", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P43", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P44", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P45", "", tokens=0, max_tokens=5)
body_main_petri_net.add_place("P46", "", tokens=0, max_tokens=5)



body_main_petri_net.add_transition("T1", {}, {"P1": 1, "P25": 1, "P37": 1})
body_main_petri_net.add_transition("T2", {"P1": 1}, {"P2": 1, "P10": 1, "P14": 1})
body_main_petri_net.add_transition("T3", {"P2": 1}, {"P3": 1})
body_main_petri_net.add_transition("T4", {"P3": 1}, {"P4": 1})
body_main_petri_net.add_transition("T5", {"P4": 1}, {"P5": 1})
body_main_petri_net.add_transition("T6", {"P5": 1, "P12": 1, "P20": 1}, {"P6": 1})
body_main_petri_net.add_transition("T7", {"P6": 1, "P31": 1}, {"P7": 1})
body_main_petri_net.add_transition("T8", {"P7": 1}, {})
body_main_petri_net.add_transition("T9", {"P3": 1}, {"P8": 1})
body_main_petri_net.add_transition("T10", {"P8": 1}, {"P5": 1})
body_main_petri_net.add_transition("T11", {"P2": 1}, {"P9": 1})
body_main_petri_net.add_transition("T12", {"P9": 1}, {"P5": 1})

body_main_petri_net.add_transition("T13", {"P10": 1}, {"P11": 1})
body_main_petri_net.add_transition("T14", {"P11": 1}, {"P12": 1})
body_main_petri_net.add_transition("T15", {"P10": 1}, {"P13": 1})
body_main_petri_net.add_transition("T16", {"P13": 1}, {"P12": 1})

body_main_petri_net.add_transition("T17", {"P14": 1}, {"P15": 1})
body_main_petri_net.add_transition("T18", {"P15": 1}, {"P16": 1})
body_main_petri_net.add_transition("T19", {"P16": 1}, {"P17": 1})
body_main_petri_net.add_transition("T20", {"P17": 1}, {"P18": 1})
body_main_petri_net.add_transition("T21", {"P18": 1}, {"P19": 1})
body_main_petri_net.add_transition("T22", {"P19": 1}, {"P20": 1})
body_main_petri_net.add_transition("T23", {"P14": 1}, {"P21": 1})
body_main_petri_net.add_transition("T24", {"P21": 1}, {"P16": 1})
body_main_petri_net.add_transition("T25", {"P16": 1}, {"P22": 1})
body_main_petri_net.add_transition("T26", {"P22": 1}, {"P18": 1})
body_main_petri_net.add_transition("T27", {"P18": 1}, {"P23": 1})
body_main_petri_net.add_transition("T28", {"P23": 1}, {"P20": 1})
body_main_petri_net.add_transition("T29", {"P18": 1}, {"P24": 1})
body_main_petri_net.add_transition("T30", {"P24": 1}, {"P20": 1})

body_main_petri_net.add_transition("T31", {"P25": 1}, {"P26": 1})
body_main_petri_net.add_transition("T32", {"P26": 1}, {"P27": 1})
body_main_petri_net.add_transition("T33", {"P27": 1}, {"P28": 1})
body_main_petri_net.add_transition("T34", {"P28": 1}, {"P29": 1})
body_main_petri_net.add_transition("T35", {"P29": 1}, {"P30": 1})
body_main_petri_net.add_transition("T36", {"P30": 1}, {"P31": 1})
body_main_petri_net.add_transition("T37", {"P25": 1}, {"P32": 1})
body_main_petri_net.add_transition("T38", {"P32": 1}, {"P27": 1})
body_main_petri_net.add_transition("T39", {"P27": 1}, {"P33": 1})
body_main_petri_net.add_transition("T40", {"P33": 1}, {"P29": 1})
body_main_petri_net.add_transition("T41", {"P29": 1}, {"P34": 1})
body_main_petri_net.add_transition("T42", {"P34": 1}, {"P31": 1})
body_main_petri_net.add_transition("T43", {"P25": 1}, {"P35": 1})
body_main_petri_net.add_transition("T44", {"P35": 1}, {"P27": 1})
body_main_petri_net.add_transition("T45", {"P29": 1}, {"P36": 1})
body_main_petri_net.add_transition("T46", {"P36": 1}, {"P31": 1})
