from petri_nets.PetrisNet import PetriNet

cup_main_petri_net = PetriNet()

cup_main_petri_net.add_place("P1", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P2", tokens=2, max_tokens=3)
cup_main_petri_net.add_place("P3", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P4", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P5", tokens=10, max_tokens=10)
cup_main_petri_net.add_place("P10", tokens=2, max_tokens=2)
cup_main_petri_net.add_place("P11", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P16", tokens=3, max_tokens=3)
cup_main_petri_net.add_place("P17", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P20", tokens=2, max_tokens=2)
cup_main_petri_net.add_place("P21", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P26", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P29", tokens=2, max_tokens=2)
cup_main_petri_net.add_place("P30", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P35", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P6", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P7", tokens=10, max_tokens=5)
cup_main_petri_net.add_place("P12", tokens=2, max_tokens=2)
cup_main_petri_net.add_place("P13", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P18", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P22", tokens=2, max_tokens=2)
cup_main_petri_net.add_place("P23", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P27", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P31", tokens=2, max_tokens=2)
cup_main_petri_net.add_place("P32", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P36", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P38", tokens=0, max_tokens=5)
cup_main_petri_net.add_place("P39", tokens=0, max_tokens=5)

cup_main_petri_net.add_transition("T1", {}, {"P1": 1})
cup_main_petri_net.add_transition("T2", {"P1": 1, "P2": 1}, {"P3": 1})
cup_main_petri_net.add_transition("T3", {"P3": 1}, {"P4": 1})
cup_main_petri_net.add_transition("T6", {"P4": 1, "P5": 1, "P10": 1}, {"P11": 1})
cup_main_petri_net.add_transition("T9", {"P11": 1}, {"P17": 1})
cup_main_petri_net.add_transition("T12", {"P16": 1, "P17": 1, "P20": 1}, {"P10": 1, "P21": 1})
cup_main_petri_net.add_transition("T15", {"P21": 1}, {"P26": 1})
cup_main_petri_net.add_transition("T18", {"P16": 1, "P26": 1, "P29": 1}, {"P16": 1, "P20": 1, "P30": 1})
cup_main_petri_net.add_transition("T21", {"P30": 1}, {"P35": 1})
cup_main_petri_net.add_transition("T24", {"P35": 1}, {"P29": 1, "P38": 1})
cup_main_petri_net.add_transition("T4", {"P3": 1}, {"P6": 1})
cup_main_petri_net.add_transition("T7", {"P6": 1, "P7": 1, "P12": 1}, {"P13": 1})
cup_main_petri_net.add_transition("T10", {"P13": 1}, {"P18": 1})
cup_main_petri_net.add_transition("T13", {"P16":1, "P18": 1, "P22": 1}, {"P12": 1, "P23": 1})
cup_main_petri_net.add_transition("T16", {"P23": 1}, {"P27": 1})
cup_main_petri_net.add_transition("T19", {"P16":1, "P27": 1, "P31": 1}, {"P16": 1, "P22": 1, "P32": 1})
cup_main_petri_net.add_transition("T22", {"P32": 1}, {"P36": 1})
cup_main_petri_net.add_transition("T25", {"P36": 1}, {"P31": 1, "P38": 1})
cup_main_petri_net.add_transition("T27", {"P38": 1}, {"P2": 1, "P16": 1, "P39": 1})
cup_main_petri_net.add_transition("T28", {"P39": 1}, {})